// E-Commerce Product Catalog - Updated for New Database Schema
// 47 Products across Men's Clothing, Women's Clothing, and Electronics
// Schema aligned with PRODUCT table: id, name, description, price, category, image_url, stock, is_active, created_at

// Helper function to generate timestamps (simulating creation dates)
const generateCreatedAt = (monthsAgo = 0) => {
    const date = new Date('2026-01-12T21:57:28+05:30');
    date.setMonth(date.getMonth() - monthsAgo);
    return date.toISOString();
};

// Categories structure
const CATEGORIES = {
    men: { name: "Men", subcategories: ["Shirts", "T-Shirts", "Pants"] },
    women: { name: "Women", subcategories: ["Tops", "Sweaters", "Pants"] },
    electronics: { name: "Electronics", subcategories: ["Laptops", "Mobiles", "Headphones"] }
};

const PRODUCTS = [
    // MEN'S SHIRTS (14 products)
    {
        id: 1,
        name: "Azure Linen Classic",
    price: 1299,
        originalPrice: 1999,
            category: "men",
                subcategory: "Shirts",
                    image_url: "./product images/1.jpeg",
                        rating: 4.6,
                            reviews: 128,
                                description: "Elevate your casual wardrobe with this premium navy linen shirt. Crafted from 100% pure linen, it offers exceptional breathability and a relaxed fit perfect for warm days. The classic collar and button-down design make it versatile for both casual outings and semi-formal occasions.",
                                    features: ["100% Pure Linen", "Breathable Fabric", "Classic Fit", "Easy Care", "Wrinkle-Resistant Finish"],
                                        sizes: ["S", "M", "L", "XL", "XXL"],
                                            colors: ["Navy", "White", "Beige"],
                                                stock: 45,
                                                    tag: "Bestseller",
                                                        is_active: true,
                                                            created_at: generateCreatedAt(3)
    },
{
    id: 2,
        name: "Vintage Plaid Overshirt",
            price: 1899,
                originalPrice: 2799,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/2.jpeg",
                                rating: 4.7,
                                    reviews: 95,
                                        description: "Channel retro vibes with this heavyweight plaid overshirt. Perfect as a layering piece or standalone jacket, it features dual chest pockets and a relaxed, oversized fit. The premium cotton-blend fabric ensures durability and warmth.",
                                            features: ["Cotton Blend", "Oversized Fit", "Dual Chest Pockets", "Button Closure", "Machine Washable"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["Cream/Black", "Navy/Red", "Green/Brown"],
                                                        stock: 32,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 3,
        name: "Midnight Denim Casual",
            price: 1499,
                originalPrice: 2199,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/3.jpeg",
                                rating: 4.5,
                                    reviews: 156,
                                        description: "A wardrobe essential that never goes out of style. This dark denim shirt features a modern slim fit with a chest pocket and button-down collar. The soft-washed fabric gets better with every wear.",
                                            features: ["Soft-Washed Denim", "Slim Fit", "Chest Pocket", "Fade-Resistant", "Comfortable Stretch"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Dark Indigo", "Light Blue", "Black"],
                                                        stock: 58,
                                                            tag: "Core",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 4,
        name: "Sky Blue Linen Breeze",
            price: 1199,
                originalPrice: 1899,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/4.jpeg",
                                rating: 4.8,
                                    reviews: 203,
                                        description: "Experience ultimate comfort with this light blue linen shirt. The relaxed fit and breathable fabric make it ideal for summer days. Features a mandarin collar for a contemporary twist on classic design.",
                                            features: ["Lightweight Linen", "Mandarin Collar", "Relaxed Fit", "Quick Dry", "Anti-Bacterial"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Sky Blue", "Mint Green", "Coral"],
                                                        stock: 67,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 5,
        name: "Olive Linen Summer Shirt",
            price: 1199,
                originalPrice: 1799,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/5.jpeg",
                                rating: 4.5,
                                    reviews: 112,
                                        description: "Lightweight olive linen shirt perfect for summer. Features a relaxed fit and breathable fabric that keeps you cool all day. The earthy tone pairs beautifully with neutral bottoms.",
                                            features: ["100% Linen", "Breathable", "Relaxed Fit", "Summer Essential", "Natural Dye"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Olive", "Khaki", "Sand"],
                                                        stock: 56,
                                                            tag: "Summer",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 6,
        name: "Textured Navy Short Sleeve",
            price: 999,
                originalPrice: 1599,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/6.jpeg",
                                rating: 4.4,
                                    reviews: 89,
                                        description: "Stand out with this textured short-sleeve shirt featuring a unique waffle-knit pattern. Perfect for casual Fridays or weekend brunches. The breathable fabric keeps you cool while looking sharp.",
                                            features: ["Waffle-Knit Texture", "Short Sleeve", "Regular Fit", "Moisture-Wicking", "Easy Iron"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["Navy", "Charcoal", "Olive"],
                                                        stock: 41,
                                                            tag: "Casual",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 7,
        name: "Forest Green Essential",
            price: 1399,
                originalPrice: 2099,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/7.jpeg",
                                rating: 4.6,
                                    reviews: 142,
                                        description: "A versatile forest green linen shirt that transitions seamlessly from day to night. The classic design features a chest pocket and mother-of-pearl buttons for an elevated look.",
                                            features: ["Premium Linen", "Classic Collar", "Chest Pocket", "Pearl Buttons", "Tailored Fit"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Forest Green", "Burgundy", "Mustard"],
                                                        stock: 39,
                                                            tag: "Trending",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 31,
        name: "Striped Casual Shirt",
            price: 1299,
                originalPrice: 1899,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/33.jpeg",
                                rating: 4.4,
                                    reviews: 87,
                                        description: "Classic striped shirt in soft cotton. Timeless design that works for any occasion. The vertical stripes create a slimming effect while the comfortable fabric ensures all-day wearability.",
                                            features: ["Cotton Fabric", "Classic Stripes", "Regular Fit", "Easy Care", "Versatile"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Blue/White", "Black/White", "Grey/White"],
                                                        stock: 48,
                                                            tag: "Classic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 38,
        name: "Denim Jacket Classic",
            price: 2299,
                originalPrice: 3499,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/7144.jpeg",
                                rating: 4.8,
                                    reviews: 312,
                                        description: "Timeless denim jacket in classic blue wash. A wardrobe staple that never goes out of style. Features button front, chest pockets, and durable construction that improves with age.",
                                            features: ["Classic Denim", "Button Front", "Chest Pockets", "Durable", "Vintage Wash"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Blue Wash", "Black", "Light Wash"],
                                                        stock: 56,
                                                            tag: "Classic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 46,
        name: "Beige Casual Blazer",
            price: 3499,
                originalPrice: 5299,
                    category: "men",
                        subcategory: "Shirts",
                            image_url: "./product images/ssdsdsd.jpeg",
                                rating: 4.7,
                                    reviews: 156,
                                        description: "Sophisticated beige blazer for smart-casual occasions. Tailored fit with premium fabric blend. Perfect for elevating your everyday look or dressing up for events.",
                                            features: ["Tailored Fit", "Premium Fabric", "Two-Button", "Notch Lapel", "Lined Interior"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Beige", "Navy", "Charcoal"],
                                                        stock: 28,
                                                            tag: "Formal",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// MEN'S T-SHIRTS & POLOS (8 products)
{
    id: 8,
        name: "California Graphic Tee",
            price: 699,
                originalPrice: 1099,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/8.jpeg",
                                rating: 4.3,
                                    reviews: 267,
                                        description: "Express your style with this vintage-inspired California graphic tee. Made from premium cotton with a comfortable regular fit. The retro print adds character to any casual outfit.",
                                            features: ["100% Cotton", "Screen Print", "Regular Fit", "Pre-Shrunk", "Soft Hand Feel"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Brown", "Black", "White"],
                                                        stock: 92,
                                                            tag: "Bestseller",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 9,
        name: "Striped Rugby Polo",
            price: 1099,
                originalPrice: 1699,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/9.jpeg",
                                rating: 4.5,
                                    reviews: 134,
                                        description: "Classic rugby-style polo with bold navy and white stripes. Features a ribbed collar and long sleeves for a sporty yet refined look. Perfect for layering or wearing solo.",
                                            features: ["Rugby Stripes", "Ribbed Collar", "Long Sleeve", "Cotton Pique", "Relaxed Fit"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["Navy/White", "Green/White", "Red/White"],
                                                        stock: 54,
                                                            tag: "Sport",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 10,
        name: "Premium Polo Contrast",
            price: 999,
                originalPrice: 1499,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/10.jpeg",
                                rating: 4.7,
                                    reviews: 178,
                                        description: "Sophisticated brown polo with cream contrast collar and pocket detail. The premium cotton blend ensures comfort and durability. A modern take on the classic polo shirt.",
                                            features: ["Contrast Collar", "Chest Pocket", "Cotton Blend", "Moisture-Wicking", "Fade-Resistant"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Brown/Cream", "Navy/White", "Black/Grey"],
                                                        stock: 48,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 11,
        name: "Raglan Baseball Tee",
            price: 799,
                originalPrice: 1199,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/11.jpeg",
                                rating: 4.4,
                                    reviews: 221,
                                        description: "Classic baseball-style tee with contrasting raglan sleeves. The comfortable cotton fabric and relaxed fit make it perfect for everyday wear. A timeless casual essential.",
                                            features: ["Raglan Sleeves", "Contrast Colors", "100% Cotton", "Crew Neck", "Regular Fit"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["White/Navy", "Grey/Black", "White/Burgundy"],
                                                        stock: 76,
                                                            tag: "Classic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 12,
        name: "Phoenix Graphic Tee",
            price: 799,
                originalPrice: 1299,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/12.jpeg",
                                rating: 4.6,
                                    reviews: 189,
                                        description: "Make a statement with this bold phoenix back print tee. The striking red design on premium white cotton creates a unique look. Perfect for those who dare to stand out.",
                                            features: ["Back Print Design", "Premium Cotton", "Oversized Fit", "Soft Fabric", "Statement Piece"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["White/Red", "Black/Gold", "Grey/Blue"],
                                                        stock: 63,
                                                            tag: "Limited",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 28,
        name: "Minimalist White Tee",
            price: 599,
                originalPrice: 999,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/23.jpeg",
                                rating: 4.7,
                                    reviews: 445,
                                        description: "Essential white crew neck tee in premium cotton. The perfect base layer for any outfit. Classic fit that works with everything from jeans to chinos.",
                                            features: ["Premium Cotton", "Crew Neck", "Regular Fit", "Versatile", "Pre-Shrunk"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["White", "Black", "Grey"],
                                                        stock: 120,
                                                            tag: "Essential",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 30,
        name: "Grey Melange Hoodie",
            price: 1899,
                originalPrice: 2799,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/30.jpeg",
                                rating: 4.8,
                                    reviews: 298,
                                        description: "Comfortable grey hoodie with kangaroo pocket. Perfect for casual days and layering. The soft fleece interior provides warmth without bulk.",
                                            features: ["Cotton Blend", "Kangaroo Pocket", "Drawstring Hood", "Ribbed Cuffs", "Fleece Lined"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["Grey", "Black", "Navy"],
                                                        stock: 73,
                                                            tag: "Comfort",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 33,
        name: "Navy Henley Tee",
            price: 899,
                originalPrice: 1399,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/36.jpeg",
                                rating: 4.6,
                                    reviews: 234,
                                        description: "Classic henley with button placket. Versatile piece that elevates casual looks. The three-button design adds a refined touch to the casual silhouette.",
                                            features: ["Button Placket", "Soft Cotton", "Regular Fit", "Casual Style", "Long Sleeve"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Navy", "Grey", "White"],
                                                        stock: 91,
                                                            tag: "Casual",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 39,
        name: "Graphic Print Tee",
            price: 799,
                originalPrice: 1199,
                    category: "men",
                        subcategory: "T-Shirts",
                            image_url: "./product images/8787878.jpeg",
                                rating: 4.4,
                                    reviews: 223,
                                        description: "Bold graphic print tee for statement style. Premium cotton with vibrant prints that don't fade. Express your personality with eye-catching designs.",
                                            features: ["Graphic Print", "Cotton Fabric", "Regular Fit", "Statement Piece", "Fade-Resistant"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Multi", "Black", "White"],
                                                        stock: 67,
                                                            tag: "Bold",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// MEN'S PANTS (9 products)
{
    id: 13,
        name: "Urban Wide-Leg Charcoal",
            price: 1699,
                originalPrice: 2499,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/15.jpeg",
                                rating: 4.8,
                                    reviews: 145,
                                        description: "Embrace the wide-leg trend with these charcoal grey pants. The relaxed silhouette and premium fabric blend offer both style and comfort. Features an elastic waistband for easy wear.",
                                            features: ["Wide-Leg Cut", "Elastic Waist", "Premium Blend", "Side Pockets", "Relaxed Fit"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Charcoal", "Black", "Navy"],
                                                        stock: 42,
                                                            tag: "Trending",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 14,
        name: "Corduroy Comfort Brown",
            price: 1799,
                originalPrice: 2699,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/16.jpeg",
                                rating: 4.7,
                                    reviews: 98,
                                        description: "Vintage-inspired corduroy pants in rich brown. The soft, ribbed texture and wide-leg design create a retro aesthetic. Perfect for adding character to your wardrobe.",
                                            features: ["Corduroy Fabric", "Wide-Leg", "Multiple Pockets", "Adjustable Waist", "Vintage Style"],
                                                sizes: ["30", "32", "34", "36", "38"],
                                                    colors: ["Brown", "Olive", "Burgundy"],
                                                        stock: 36,
                                                            tag: "Retro",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 15,
        name: "Cargo Utility Beige",
            price: 1599,
                originalPrice: 2399,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/17.jpeg",
                                rating: 4.5,
                                    reviews: 167,
                                        description: "Functional meets fashionable with these beige cargo pants. Multiple pockets provide practical storage while the relaxed fit ensures all-day comfort. A modern streetwear essential.",
                                            features: ["Cargo Pockets", "Durable Fabric", "Relaxed Fit", "Adjustable Hem", "Utility Style"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Beige", "Olive", "Black"],
                                                        stock: 71,
                                                            tag: "Utility",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 16,
        name: "Classic Beige Chinos",
            price: 1499,
                originalPrice: 2199,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/13.jpeg",
                                rating: 4.6,
                                    reviews: 234,
                                        description: "Timeless beige chinos that belong in every man's wardrobe. The straight-leg cut and premium cotton twill fabric offer versatility for both casual and smart-casual occasions.",
                                            features: ["Cotton Twill", "Straight Leg", "Belt Loops", "Zip Fly", "Classic Fit"],
                                                sizes: ["28", "30", "32", "34", "36", "38"],
                                                    colors: ["Beige", "Navy", "Olive"],
                                                        stock: 88,
                                                            tag: "Essential",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 17,
        name: "Relaxed Grey Joggers",
            price: 1299,
                originalPrice: 1899,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/14.jpeg",
                                rating: 4.4,
                                    reviews: 312,
                                        description: "Ultimate comfort meets contemporary style with these grey joggers. The soft fabric and relaxed fit make them perfect for lounging or casual outings. Features an adjustable drawstring waist.",
                                            features: ["Soft Fabric", "Drawstring Waist", "Side Pockets", "Tapered Leg", "Comfortable Fit"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Grey", "Black", "Navy"],
                                                        stock: 95,
                                                            tag: "Comfort",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 18,
        name: "Vintage Wash Denim",
            price: 1899,
                originalPrice: 2899,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/18.jpeg",
                                rating: 4.7,
                                    reviews: 201,
                                        description: "Classic denim with a vintage wash finish. The relaxed straight-leg cut and premium denim fabric ensure lasting quality. A versatile piece that pairs with everything.",
                                            features: ["Vintage Wash", "Straight Leg", "5-Pocket Design", "Button Fly", "Durable Denim"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Vintage Blue", "Black", "Light Wash"],
                                                        stock: 52,
                                                            tag: "Denim",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 29,
        name: "Black Slim Chinos",
            price: 1599,
                originalPrice: 2299,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/29.jpeg",
                                rating: 4.6,
                                    reviews: 189,
                                        description: "Sleek black chinos with a modern slim fit. Versatile enough for office or evening wear. The stretch cotton blend ensures comfort without sacrificing style.",
                                            features: ["Slim Fit", "Stretch Cotton", "Zip Fly", "4-Pocket Design", "Versatile"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Black", "Navy", "Charcoal"],
                                                        stock: 64,
                                                            tag: "Versatile",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 32,
        name: "Khaki Cargo Shorts",
            price: 1199,
                originalPrice: 1799,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/35.jpeg",
                                rating: 4.3,
                                    reviews: 156,
                                        description: "Practical khaki cargo shorts with multiple pockets. Perfect for outdoor activities and summer adventures. Durable fabric that withstands active wear.",
                                            features: ["Cargo Pockets", "Durable Fabric", "Adjustable Waist", "Utility Style", "Quick Dry"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Khaki", "Olive", "Navy"],
                                                        stock: 82,
                                                            tag: "Outdoor",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 40,
        name: "Slim Fit Jeans",
            price: 1999,
                originalPrice: 2999,
                    category: "men",
                        subcategory: "Pants",
                            image_url: "./product images/sd.jpeg",
                                rating: 4.7,
                                    reviews: 445,
                                        description: "Modern slim fit jeans in dark wash. Comfortable stretch denim for all-day wear. The tapered leg creates a contemporary silhouette.",
                                            features: ["Stretch Denim", "Slim Fit", "5-Pocket", "Dark Wash", "Tapered Leg"],
                                                sizes: ["28", "30", "32", "34", "36"],
                                                    colors: ["Dark Blue", "Black", "Grey"],
                                                        stock: 89,
                                                            tag: "Modern",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// WOMEN'S TOPS (3 products)
{
    id: 19,
        name: "Burgundy Ruched Elegance",
            price: 899,
                originalPrice: 1499,
                    category: "women",
                        subcategory: "Tops",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.02 PM.jpeg",
                                rating: 4.8,
                                    reviews: 156,
                                        description: "Sophisticated burgundy top with elegant ruching detail at the waist. The fitted silhouette and long sleeves create a flattering look perfect for evening wear or special occasions.",
                                            features: ["Ruched Waist", "Long Sleeve", "Fitted Cut", "Stretch Fabric", "Elegant Design"],
                                                sizes: ["XS", "S", "M", "L", "XL"],
                                                    colors: ["Burgundy", "Black", "Navy"],
                                                        stock: 44,
                                                            tag: "Elegant",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 35,
        name: "Black Fitted Top",
            price: 799,
                originalPrice: 1299,
                    category: "women",
                        subcategory: "Tops",
                            image_url: "./product images/38.jpeg",
                                rating: 4.5,
                                    reviews: 289,
                                        description: "Essential black fitted top with scoop neck. Versatile base for any outfit. The stretch fabric ensures a comfortable, flattering fit all day long.",
                                            features: ["Stretch Fabric", "Scoop Neck", "Fitted Cut", "Versatile", "Layering Essential"],
                                                sizes: ["XS", "S", "M", "L", "XL"],
                                                    colors: ["Black", "White", "Navy"],
                                                        stock: 105,
                                                            tag: "Essential",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// WOMEN'S SWEATERS (4 products)
{
    id: 20,
        name: "Cozy Beige Knit",
            price: 1599,
                originalPrice: 2499,
                    category: "women",
                        subcategory: "Sweaters",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.04 PM.jpegw.jpeg",
                                rating: 4.9,
                                    reviews: 223,
                                        description: "Luxuriously soft beige knit sweater with a chunky texture. The relaxed fit and ribbed details create a cozy yet stylish look. Perfect for layering during cooler months.",
                                            features: ["Chunky Knit", "Ribbed Cuffs", "Relaxed Fit", "Soft Yarn", "Warm & Cozy"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Beige", "Cream", "Grey"],
                                                        stock: 38,
                                                            tag: "Cozy",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 21,
        name: "Navy Zip Collar Sweater",
            price: 1799,
                originalPrice: 2699,
                    category: "women",
                        subcategory: "Sweaters",
                            image_url: "./product images/fg.jpeg",
                                rating: 4.7,
                                    reviews: 134,
                                        description: "Modern navy sweater featuring a unique zip collar detail. The structured design and premium knit fabric offer both warmth and style. A contemporary wardrobe essential.",
                                            features: ["Zip Collar", "Structured Fit", "Premium Knit", "Ribbed Texture", "Modern Design"],
                                                sizes: ["XS", "S", "M", "L"],
                                                    colors: ["Navy", "Black", "Charcoal"],
                                                        stock: 29,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 22,
        name: "Chocolate Turtleneck",
            price: 1499,
                originalPrice: 2199,
                    category: "women",
                        subcategory: "Sweaters",
                            image_url: "./product images/h.jpeg",
                                rating: 4.6,
                                    reviews: 178,
                                        description: "Classic chocolate brown turtleneck with a cropped silhouette. The soft ribbed fabric and balloon sleeves add a touch of drama. Perfect for creating chic layered looks.",
                                            features: ["Turtleneck", "Cropped Length", "Balloon Sleeves", "Ribbed Knit", "Soft Fabric"],
                                                sizes: ["XS", "S", "M", "L", "XL"],
                                                    colors: ["Chocolate", "Cream", "Black"],
                                                        stock: 51,
                                                            tag: "Chic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 34,
        name: "Cream Knit Cardigan",
            price: 2199,
                originalPrice: 3299,
                    category: "women",
                        subcategory: "Sweaters",
                            image_url: "./product images/37.jpeg",
                                rating: 4.9,
                                    reviews: 167,
                                        description: "Luxurious cream cardigan in soft knit. Perfect layering piece for any season. The button-front design and relaxed fit create an effortlessly elegant look.",
                                            features: ["Soft Knit", "Button Front", "Relaxed Fit", "Cozy Fabric", "Versatile"],
                                                sizes: ["XS", "S", "M", "L"],
                                                    colors: ["Cream", "Beige", "Grey"],
                                                        stock: 34,
                                                            tag: "Luxury",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 36,
        name: "Oversized Grey Sweater",
            price: 1699,
                originalPrice: 2499,
                    category: "women",
                        subcategory: "Sweaters",
                            image_url: "./product images/39.jpeg",
                                rating: 4.7,
                                    reviews: 198,
                                        description: "Cozy oversized sweater in soft grey. Perfect for relaxed weekend style. The dropped shoulders and loose fit create a comfortable, contemporary silhouette.",
                                            features: ["Oversized Fit", "Soft Yarn", "Ribbed Details", "Comfortable", "Relaxed Style"],
                                                sizes: ["S", "M", "L"],
                                                    colors: ["Grey", "Beige", "Black"],
                                                        stock: 42,
                                                            tag: "Cozy",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// WOMEN'S PANTS (1 product)
{
    id: 37,
        name: "White Linen Pants",
            price: 1799,
                originalPrice: 2699,
                    category: "women",
                        subcategory: "Pants",
                            image_url: "./product images/5454.jpeg",
                                rating: 4.6,
                                    reviews: 134,
                                        description: "Elegant white linen pants with wide leg. Perfect for summer elegance. The breathable fabric and relaxed fit make these ideal for warm weather.",
                                            features: ["Pure Linen", "Wide Leg", "Elastic Waist", "Breathable", "Summer Essential"],
                                                sizes: ["XS", "S", "M", "L", "XL"],
                                                    colors: ["White", "Beige", "Navy"],
                                                        stock: 38,
                                                            tag: "Summer",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// ELECTRONICS - LAPTOPS (4 products)
{
    id: 23,
        name: "MacBook Air M2",
            price: 99999,
                originalPrice: 119999,
                    category: "electronics",
                        subcategory: "Laptops",
                            image_url: "./product images/20.jpeg",
                                rating: 4.9,
                                    reviews: 1247,
                                        description: "The incredibly thin and light MacBook Air is now more powerful than ever. The Apple M2 chip delivers exceptional performance and battery life. Features a stunning Liquid Retina display and advanced camera.",
                                            features: ["M2 Chip", "13.6\" Retina Display", "18hr Battery", "8GB RAM", "256GB SSD"],
                                                sizes: ["256GB", "512GB"],
                                                    colors: ["Space Grey", "Silver", "Starlight", "Midnight"],
                                                        stock: 15,
                                                            tag: "Premium",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 24,
        name: "MacBook Pro 14\"",
            price: 189999,
                originalPrice: 219999,
                    category: "electronics",
                        subcategory: "Laptops",
                            image_url: "./product images/22.jpeg",
                                rating: 5.0,
                                    reviews: 892,
                                        description: "Professional-grade performance meets stunning design. The MacBook Pro with M2 Pro chip delivers extraordinary power for demanding workflows. Features Liquid Retina XDR display.",
                                            features: ["M2 Pro Chip", "14\" XDR Display", "20hr Battery", "16GB RAM", "512GB SSD"],
                                                sizes: ["512GB", "1TB"],
                                                    colors: ["Space Grey", "Silver"],
                                                        stock: 8,
                                                            tag: "Pro",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 25,
        name: "HP Pavilion 15",
            price: 54999,
                originalPrice: 69999,
                    category: "electronics",
                        subcategory: "Laptops",
                            image_url: "./product images/19.jpeg",
                                rating: 4.4,
                                    reviews: 567,
                                        description: "Reliable performance for everyday computing. Features Intel Core i5 processor, Full HD display, and all-day battery life. Perfect for students and professionals.",
                                            features: ["Intel i5 11th Gen", "15.6\" FHD", "8GB RAM", "512GB SSD", "Windows 11"],
                                                sizes: ["512GB", "1TB"],
                                                    colors: ["Silver", "Natural Silver"],
                                                        stock: 32,
                                                            tag: "Value",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 26,
        name: "Samsung Galaxy Book2",
            price: 64999,
                originalPrice: 79999,
                    category: "electronics",
                        subcategory: "Laptops",
                            image_url: "./product images/21.jpeg",
                                rating: 4.5,
                                    reviews: 423,
                                        description: "Sleek and powerful laptop with seamless Samsung ecosystem integration. Features vibrant AMOLED display and long battery life. Ideal for productivity and entertainment.",
                                            features: ["Intel i5 12th Gen", "15.6\" AMOLED", "8GB RAM", "256GB SSD", "Windows 11"],
                                                sizes: ["256GB", "512GB"],
                                                    colors: ["Graphite", "Silver"],
                                                        stock: 24,
                                                            tag: "AMOLED",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// ELECTRONICS - MOBILES (1 product)
{
    id: 27,
        name: "iPhone 13 Pro",
            price: 89999,
                originalPrice: 109999,
                    category: "electronics",
                        subcategory: "Mobiles",
                            image_url: "./product images/28.jpeg",
                                rating: 4.8,
                                    reviews: 2134,
                                        description: "Pro camera system with Cinematic mode. Super Retina XDR display with ProMotion. A15 Bionic chip for incredible performance. 5G capable for blazing-fast connectivity.",
                                            features: ["A15 Bionic", "6.1\" ProMotion", "Pro Camera", "5G", "128GB Storage"],
                                                sizes: ["128GB", "256GB", "512GB", "1TB"],
                                                    colors: ["Sierra Blue", "Graphite", "Gold", "Silver"],
                                                        stock: 18,
                                                            tag: "Flagship",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// ELECTRONICS - HEADPHONES (5 products)
{
    id: 41,
        name: "Wireless Earbuds Pro",
            price: 12999,
                originalPrice: 16999,
                    category: "electronics",
                        subcategory: "Headphones",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.03 PM.jpeg",
                                rating: 4.6,
                                    reviews: 678,
                                        description: "Premium wireless earbuds with active noise cancellation. Crystal clear sound and all-day battery life. Perfect for music lovers and professionals on the go.",
                                            features: ["ANC", "30hr Battery", "Touch Controls", "IPX4 Water Resistant", "Premium Sound"],
                                                sizes: ["One Size"],
                                                    colors: ["White", "Black"],
                                                        stock: 45,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 42,
        name: "Over-Ear Headphones",
            price: 8999,
                originalPrice: 12999,
                    category: "electronics",
                        subcategory: "Headphones",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.06 PM.jpeg",
                                rating: 4.5,
                                    reviews: 534,
                                        description: "Comfortable over-ear headphones with superior sound quality. Perfect for music lovers. Soft cushions and foldable design for portability.",
                                            features: ["40mm Drivers", "Foldable", "20hr Battery", "Soft Cushions", "Deep Bass"],
                                                sizes: ["One Size"],
                                                    colors: ["Black", "Silver"],
                                                        stock: 38,
                                                            tag: "Audio",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 43,
        name: "Gaming Headset RGB",
            price: 5999,
                originalPrice: 8999,
                    category: "electronics",
                        subcategory: "Headphones",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.06 PM.jpeg54454.jpeg",
                                rating: 4.4,
                                    reviews: 423,
                                        description: "Immersive gaming headset with RGB lighting. Crystal clear mic and surround sound. Designed for competitive gaming with comfortable ear cups.",
                                            features: ["7.1 Surround", "RGB Lighting", "Noise-Canceling Mic", "Comfortable", "USB Connection"],
                                                sizes: ["One Size"],
                                                    colors: ["Black/RGB"],
                                                        stock: 52,
                                                            tag: "Gaming",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 44,
        name: "Sport Bluetooth Earphones",
            price: 3999,
                originalPrice: 5999,
                    category: "electronics",
                        subcategory: "Headphones",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.07 PM.jpeg",
                                rating: 4.3,
                                    reviews: 567,
                                        description: "Sweat-proof earphones designed for active lifestyles. Secure fit and powerful bass. Perfect for workouts and outdoor activities.",
                                            features: ["IPX7 Waterproof", "Secure Fit", "12hr Battery", "Bass Boost", "Sport Design"],
                                                sizes: ["One Size"],
                                                    colors: ["Black", "Red", "Blue"],
                                                        stock: 78,
                                                            tag: "Sport",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 45,
        name: "Studio Monitor Headphones",
            price: 15999,
                originalPrice: 21999,
                    category: "electronics",
                        subcategory: "Headphones",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.07 sdsdsdsdsdsdsd.jpeg",
                                rating: 4.9,
                                    reviews: 234,
                                        description: "Professional studio-grade headphones for audio professionals. Accurate sound reproduction with flat frequency response. Essential for music production.",
                                            features: ["Flat Response", "Detachable Cable", "Comfortable", "Professional", "50mm Drivers"],
                                                sizes: ["One Size"],
                                                    colors: ["Black"],
                                                        stock: 22,
                                                            tag: "Pro",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},

// ACCESSORIES (1 product)
{
    id: 47,
        name: "Premium Leather Wallet",
            price: 1499,
                originalPrice: 2299,
                    category: "men",
                        subcategory: "Accessories",
                            image_url: "./product images/WhatsApp Image 2026-01-07 at 9.27.04 PM.jpesdg.jpeg",
                                rating: 4.8,
                                    reviews: 789,
                                        description: "Genuine leather wallet with RFID protection. Slim design with multiple card slots. Crafted from premium full-grain leather that ages beautifully.",
                                            features: ["Genuine Leather", "RFID Blocking", "Slim Design", "8 Card Slots", "Money Compartment"],
                                                sizes: ["One Size"],
                                                    colors: ["Brown", "Black"],
                                                        stock: 94,
                                                            tag: "Accessory",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
}
,

// WWE MERCHANDISE - T-SHIRTS
{
    id: 48,
        name: "WWE Classic Logo Tee",
            price: 899,
                originalPrice: 1299,
                    category: "wwe",
                        subcategory: "T-Shirts",
                            image_url: "./product images/wwe_tshirt_1_1768930667396.png",
                                rating: 4.7,
                                    reviews: 542,
                                        description: "Official WWE t-shirt featuring the iconic WWE logo. Made from premium cotton for maximum comfort. Perfect for wrestling fans and casual wear.",
                                            features: ["100% Cotton", "Official WWE Merch", "Screen Print Logo", "Regular Fit", "Machine Washable"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Black", "Navy", "Red"],
                                                        stock: 125,
                                                            tag: "Bestseller",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 49,
        name: "WWE Championship Belt Tee",
            price: 999,
                originalPrice: 1499,
                    category: "wwe",
                        subcategory: "T-Shirts",
                            image_url: "./product images/wwe_tshirt_2_1768930689272.png",
                                rating: 4.8,
                                    reviews: 689,
                                        description: "Show your championship spirit with this vintage-style WWE belt graphic tee. Bold design on premium fabric. Official WWE merchandise.",
                                            features: ["Vintage Design", "Championship Print", "Soft Cotton", "Crew Neck", "Official Merch"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Red", "Black", "White"],
                                                        stock: 98,
                                                            tag: "New",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 50,
        name: "WWE Scratch Logo Tee",
            price: 849,
                originalPrice: 1199,
                    category: "wwe",
                        subcategory: "T-Shirts",
                            image_url: "./product images/wwe_tshirt_3_1768930783094.png",
                                rating: 4.6,
                                    reviews: 478,
                                        description: "Modern WWE scratch logo design on premium white tee. Comfortable fit with bold graphics. Show your WWE pride in style.",
                                            features: ["Modern Design", "Scratch Logo", "Premium Cotton", "Regular Fit", "Fade Resistant"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["White", "Grey", "Black"],
                                                        stock: 87,
                                                            tag: "Trending",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 51,
        name: "WWE Tank Top",
            price: 749,
                originalPrice: 1099,
                    category: "wwe",
                        subcategory: "T-Shirts",
                            image_url: "./product images/wwe_tank_top_1768930805931.png",
                                rating: 4.5,
                                    reviews: 367,
                                        description: "Athletic WWE tank top perfect for workouts and summer wear. Breathable fabric with bold WWE logo. Comfortable athletic fit.",
                                            features: ["Athletic Fit", "Breathable", "Moisture Wicking", "Bold Logo", "Gym Ready"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Black", "Grey", "Navy"],
                                                        stock: 76,
                                                            tag: "Athletic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 52,
        name: "WWE Logo Hoodie",
            price: 1899,
                originalPrice: 2799,
                    category: "wwe",
                        subcategory: "Hoodies",
                            image_url: "./product images/wwe_hoodie_1_1768930711310.png",
                                rating: 4.9,
                                    reviews: 823,
                                        description: "Premium WWE hoodie with large logo design. Soft fleece interior and adjustable hood. Perfect for staying warm while representing WWE.",
                                            features: ["Fleece Lined", "Kangaroo Pocket", "Adjustable Hood", "Ribbed Cuffs", "Premium Quality"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Black", "Navy", "Grey"],
                                                        stock: 64,
                                                            tag: "Premium",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 53,
        name: "WWE Varsity Jacket",
            price: 3499,
                originalPrice: 4999,
                    category: "wwe",
                        subcategory: "Hoodies",
                            image_url: "./product images/wwe_jacket_1768930830314.png",
                                rating: 4.8,
                                    reviews: 456,
                                        description: "Classic varsity-style WWE jacket with premium construction. Features WWE patches and leather sleeves. Ultimate collector's piece for WWE fans.",
                                            features: ["Wool Body", "Leather Sleeves", "WWE Patches", "Button Front", "Vintage Style"],
                                                sizes: ["M", "L", "XL", "XXL"],
                                                    colors: ["Black/Grey"],
                                                        stock: 32,
                                                            tag: "Limited",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 54,
        name: "WWE Baseball Cap",
            price: 699,
                originalPrice: 999,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_cap_1_1768930732326.png",
                                rating: 4.7,
                                    reviews: 934,
                                        description: "Official WWE baseball cap with embroidered logo. Adjustable strap for perfect fit. Classic design for everyday wear.",
                                            features: ["Embroidered Logo", "Adjustable Strap", "Curved Brim", "Cotton Fabric", "One Size Fits All"],
                                                sizes: ["One Size"],
                                                    colors: ["Black", "Navy", "Red"],
                                                        stock: 156,
                                                            tag: "Bestseller",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 55,
        name: "WWE Championship Belt Replica",
            price: 4999,
                originalPrice: 6999,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_championship_belt_1768930753730.png",
                                rating: 5.0,
                                    reviews: 1234,
                                        description: "Premium WWE Championship Belt replica. Authentic design with gold plating and leather strap. Must-have for serious WWE collectors.",
                                            features: ["Official Replica", "Gold Plated", "Leather Strap", "Detailed Design", "Display Ready"],
                                                sizes: ["One Size"],
                                                    colors: ["Gold/Black"],
                                                        stock: 48,
                                                            tag: "Premium",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 56,
        name: "WWE Wristbands Set",
            price: 299,
                originalPrice: 499,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_wristbands_1768930855259.png",
                                rating: 4.6,
                                    reviews: 567,
                                        description: "Pair of WWE sweatbands with embroidered logo. Perfect for workouts or showing WWE pride. Comfortable and durable.",
                                            features: ["Pair Included", "Embroidered Logo", "Sweat Absorbent", "Elastic Fit", "Machine Washable"],
                                                sizes: ["One Size"],
                                                    colors: ["Black/Red", "White/Blue"],
                                                        stock: 234,
                                                            tag: "Accessory",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 57,
        name: "WWE Backpack",
            price: 1499,
                originalPrice: 2199,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_backpack_1768930883436.png",
                                rating: 4.7,
                                    reviews: 445,
                                        description: "Spacious WWE backpack with multiple compartments. Durable construction with padded straps. Perfect for school, gym, or travel.",
                                            features: ["Multiple Compartments", "Padded Straps", "Water Resistant", "Large Capacity", "Durable"],
                                                sizes: ["One Size"],
                                                    colors: ["Black"],
                                                        stock: 89,
                                                            tag: "Practical",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 58,
        name: "WWE Athletic Shorts",
            price: 849,
                originalPrice: 1299,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_shorts_1768930919401.png",
                                rating: 4.5,
                                    reviews: 378,
                                        description: "Comfortable WWE athletic shorts for training and leisure. Moisture-wicking fabric with WWE logo. Perfect for workouts.",
                                            features: ["Moisture Wicking", "Elastic Waist", "Side Pockets", "Lightweight", "Quick Dry"],
                                                sizes: ["S", "M", "L", "XL", "XXL"],
                                                    colors: ["Black", "Navy", "Grey"],
                                                        stock: 112,
                                                            tag: "Athletic",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 59,
        name: "WWE Beanie",
            price: 549,
                originalPrice: 799,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_beanie_1768930943639.png",
                                rating: 4.6,
                                    reviews: 289,
                                        description: "Warm WWE beanie with embroidered logo. Perfect for cold weather. Comfortable knit design that fits most head sizes.",
                                            features: ["Warm Knit", "Embroidered Logo", "Stretchy Fit", "Winter Essential", "One Size"],
                                                sizes: ["One Size"],
                                                    colors: ["Black", "Grey", "Navy"],
                                                        stock: 167,
                                                            tag: "Winter",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 60,
        name: "WWE Training Gloves",
            price: 899,
                originalPrice: 1399,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_gloves_1768930964957.png",
                                rating: 4.7,
                                    reviews: 423,
                                        description: "Professional WWE fingerless training gloves. Durable construction with wrist support. Perfect for intense workouts and training.",
                                            features: ["Fingerless Design", "Wrist Support", "Padded Palm", "Breathable", "Adjustable Strap"],
                                                sizes: ["S", "M", "L", "XL"],
                                                    colors: ["Black"],
                                                        stock: 78,
                                                            tag: "Training",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 61,
        name: "WWE Championship Poster",
            price: 399,
                originalPrice: 699,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_poster_1768930991164.png",
                                rating: 4.8,
                                    reviews: 567,
                                        description: "High-quality WWE Championship poster. Perfect for decorating your room or office. Premium print quality with vibrant colors.",
                                            features: ["Premium Print", "High Quality", "Vibrant Colors", "Frame Ready", "18x24 inches"],
                                                sizes: ["18x24"],
                                                    colors: ["Multi"],
                                                        stock: 145,
                                                            tag: "Decor",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
},
{
    id: 62,
        name: "WWE Water Bottle",
            price: 599,
                originalPrice: 899,
                    category: "wwe",
                        subcategory: "Accessories",
                            image_url: "./product images/wwe_water_bottle_1768931019219.png",
                                rating: 4.7,
                                    reviews: 334,
                                        description: "Insulated WWE water bottle keeps drinks cold for 24 hours. Durable stainless steel with WWE logo. Perfect for gym and outdoor activities.",
                                            features: ["Stainless Steel", "Insulated", "24hr Cold", "Leak Proof", "750ml Capacity"],
                                                sizes: ["750ml"],
                                                    colors: ["Black", "Silver"],
                                                        stock: 198,
                                                            tag: "Practical",
                                                                is_active: true,
                                                                    created_at: generateCreatedAt(Math.floor(Math.random() * 6))
}
];